spring:
#  profiles:
#    active: dev

  jpa:
    show-sql: true
  thymeleaf:
    cache: false
  data:
    rest:
      detection-strategy: default
      max-page-size: 2

#security:
#  oauth2:
facebook:
    client:
      client-secret: aaf853ae0abb5cc9f448ebf66a6689b2
      access-token-uri: https://graph.facebook.com/oauth/access_token
      user-authorization-uri: https://www.facebook.com/dialog/oauth
      token-name: oauth_token
      authentication-scheme: query
      client-authentication-scheme: form
      client-id: 1391413134262958
    resource:
      user-info-uri: https://graph.facebook.com/me
github:
  client:
    clientId: 7a2b26249f8c43aa5b45
    clientSecret: 4b1045ee7bdcc678d6e5747da1812c0bfc14c9b5
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

---

spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: H2
    url:  jdbc:h2:mem:training;MODE=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS TRAINING
  cache:
    ehcache:
      config: ehcache.xml
security:
  basic:
    enabled: false
#  oauth2:
##    client:
##      client-secret: aaf853ae0abb5cc9f448ebf66a6689b2
##      access-token-uri: https://graph.facebook.com/oauth/access_token
##      user-authorization-uri: https://www.facebook.com/dialog/oauth
##      token-name: oauth_token
##      authentication-scheme: query
##      client-authentication-scheme: form
##      client-id: 1391413134262958
#    resource:
#      user-info-uri: https://graph.facebook.com/me

---
spring:
  profiles: aws
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    name: entity
    url: jdbc:mysql://entitity.c3rumte7brsm.us-east-1.rds.amazonaws.com:3306
    username: ajmalch
    password: Cholassery01