spring:
  jpa:
    show-sql: true
  thymeleaf:
    cache: false
  data:
    rest:
      detection-strategy: default
      max-page-size: 2
security:
  oauth2:
    client:
      client-secret: aaf853ae0abb5cc9f448ebf66a6689b2
      access-token-uri: https://graph.facebook.com/oauth/access_token
      user-authorization-uri: https://www.facebook.com/dialog/oauth
      token-name: oauth_token
      authentication-scheme: query
      client-authentication-scheme: form
      client-id: 1391413134262958
    resource:
      user-info-uri: https://graph.facebook.com/me
